### ISSUE TITLE
Any glaring issues?

### ISSUE THREAD

**Issue by Web-Cam** [Web-Cam/TestAPI#1]
I need some help, I am trying to make an Alexa work with some API, however there is an error in the code. I believe it is here.

 ```
'LaunchRequest': function () {
	rhyme = request.datamuse.words.datamuse.ask_user; //set var rhyme to pull a request from API
	function getRhyme()
	this.emit('SayRhyme');
    },
    'RhymeIntent': function () {   //used to actually say the rhyme
        this.emit('SayRhyme')
```

Any help is appreciated!

**Comment by Rud156** [comment]
Shoudn't changing `function getRhyme()` to `getRhyme()` work

**Comment by sophiekoonin** [comment]
`function getRhyme()`

Are you trying to declare or call this function here? if you're trying to call it, you don't need 'function' at the beginning.
